-- Clique.lua
-- @Author : Dencer (tdaddon@163.com)
-- @Link   : https://dengsir.github.io
-- @Date   : 8/11/2026, 2:06:01 PM
--
---@type ns
local ns = select(2, ...)

ns.addon('Clique', function()
    ns.hook(Clique, 'SetupDatabase', function(orig, ...)
        setfenv(orig, setmetatable({
            LibStub = function(name, ...)
                if name == 'AceDB-3.0' then
                    local AceDB = LibStub('AceDB-3.0', ...)

                    return setmetatable({
                        New = function(_, n, default)
                            local classKey = UnitClass('player')
                            return LibStub('AceDB-3.0'):New(n, default, classKey)
                        end,
                    }, {__index = AceDB})
                else
                    return LibStub(name, ...)
                end
            end,

        }, {__index = _G}))

        return orig(...)
    end)

    if GetLocale() == 'zhCN' then

        Clique:RegisterLocale('zhCN', {
            ['A binding that belongs to the \'default\' binding-set will always be active on your unit frames, unless you override it with another binding.'] = '默认组别，设置将对所有框体有效，除非有其他组别的相同按键设置。',
            ['A binding that belongs to the \'enemy\' binding-set will always be active when clicking on unit frames that display enemy units, i.e. those you can attack. If you click on a unit that you cannot attack, nothing will happen.'] = '敌对组别，设置只对敌对的框体有效，当你对敌对的框体点击施法时，这个设置将被触发。',
            ['A binding that belongs to the \'friend\' binding-set will only be active when clicking on unit frames that display friendly units, i.e. those you can heal and assist. If you click on a unit that you cannot heal or assist, nothing will happen.'] = '友善组别，该组别设置只对友善的框体有效，当你对友善的框体点击施法时，该设置将被触发。',
            ['A binding that belongs to the \'global\' binding-set is always active. If the spell requires a target, you will be given the \'casting hand\', otherwise the spell will be cast. If the spell is an AOE spell, you will be given the ground targeting circle.'] = '全局组别，该组别设置始终生效。如果法术需要目标，则会使用“施法手”作为目标；否则将直接施放。如果是群体法术，则会显示地面目标圈。',
            ['A binding that belongs to the \'hovercast\' binding-set is active whenever the mouse is over a unit frame, or a character in the 3D world. This allows you to use \'hovercasting\', where you hover over a unit in the world and press a key to cast a spell on them. These bindings are also active over unit frames.'] = '悬浮施法组别，当鼠标悬停在单位框体或 3D 世界中的角色上时，该组别绑定会生效。这允许你使用“悬浮施法”——将鼠标悬停在目标上并按下按键来施法。这些绑定同样在单位框体上生效。',
            ['A binding that belongs to the \'ooc\' binding-set will only be active when the player is out-of-combat, regardless of the other binding-sets this binding belongs to. As soon as the player enters combat, these bindings will no longer be active, so be careful when choosing this binding-set for any spells you use frequently.'] = '非战斗组别，该组别设置仅在玩家不在战斗中时生效。只要玩家进入战斗，这些绑定就会失效，因此请谨慎为常用技能选择这个组别。',
            ['A binding that belongs to this binding-set is only active when the player has the given talent specialization active'] = '该组别绑定仅在玩家当前激活指定天赋专精时生效。',
            ['Account Macro'] = '账号宏',
            ['Active for talent spec: %s (|cffffd100%s|r)'] = '对天赋专精 %s 生效 (|cffffd100%s|r)',
            ['Active on unit frames (|cffffd100default|r)'] = '对单位框体生效 (|cffffd100default|r)',
            ['Add Binding'] = '添加绑定',
            ['Add new profile'] = '添加新配置',
            ['Add to existing bindings'] = '添加到现有绑定',
            ['Added %d bindings to current profile'] = '已向当前配置添加 %d 个绑定',
            ['Added \'%s\' to \'%s\''] = '已将“%s”添加到“%s”',
            ['All'] = '全部',
            ['Alt'] = 'Alt',
            ['Always active, will override game bindings (|cffffd100global|r)'] = '始终生效，会覆盖游戏自带绑定 (|cffffd100global|r)',
            ['Arena enemy frames'] = '竞技场敌对框体',
            ['Attempt to fix the issue introduced in 4.3 with casting on dead targets'] = '修复 4.3 版本引入的对已死亡目标施法问题',
            ['Back'] = '返回',
            ['Blizzard Frame Options'] = '暴雪框体选项',
            ['Boss target frames'] = '首领目标框体',
            ['Both Up/Down'] = '上下都触发',
            ['Cancel'] = '取消',
            ['Cannot change profiles while in combat lockdown'] = '战斗中无法切换配置',
            ['Cannot find profile \'%s\''] = '找不到配置“%s”',
            ['Cast %s'] = '施放 %s',
            ['Change binding'] = '修改绑定',
            ['Change the \'self cast\' key under Options > Combat, or edit the binding to use a different modifier.'] = '请在“选项 > 战斗”中修改“自我施法”按键，或编辑绑定以使用不同的修饰键。',
            ['Character Macro'] = '角色宏',
            ['Click to open the in-game Click-Casting settings.'] = '点击打开游戏内点击施法设置。',
            ['Clique Bindings'] = 'Clique 绑定',
            ['Clique config UI can\'t be opened while you are in combat.'] = '战斗中无法打开 Clique 设置界面。',
            ['Clique now requires you to explicitly bind \'Target unit\' and \'Show unit menu\' actions, due to a change made by Blizzard that is breaking unit frames and click-casting addons.'] = '由于暴雪的改动会破坏单位框体和点击施法插件，Clique 现在要求你显式绑定“目标单位”和“显示单位菜单”动作。',
            ['Clique-%s'] = 'Clique-%s',
            ['Clique: \'default\' binding-set'] = '组别：默认',
            ['Clique: \'enemy\' binding-set'] = '组别：敌对',
            ['Clique: \'friend\' binding-set'] = '组别：友善',
            ['Clique: \'global\' binding-set'] = '组别：全局',
            ['Clique: \'hovercast\' binding-set'] = '组别：悬浮施法',
            ['Clique: \'ooc\' binding-set'] = '组别：非战斗',
            ['Clique: Talent binding-set for \'%s\''] = '组别：%s 的天赋绑定集',
            ['Clique: This change requires a UI reload to take effect.'] = '此改动需要重载界面后才能生效。',
            ['Compact raid frames'] = '团队框体',
            ['Conflict with your \'self cast\' key'] = '与你的“自我施法”按键冲突',
            ['Create a custom macro using the text box below. You may need to specify the target of any actions using the \'mouseover\' unit, which will be the unit that you click on. For example:\n\n/cast [target=mouseover] Regrowth\n/cast [@mouseover] Regrowth\n/cast [@cursor] Blizzard'] = '请使用下面的文本框创建自定义宏。你可能需要使用 \'mouseover\' 单位来指定任何动作的目标，这个单位就是你点击的目标。例如：\n\n/cast [target=mouseover] 愈合\n/cast [@mouseover] 愈合\n/cast [@cursor] 暴风雪',
            ['Created and switched to new profile: %s'] = '已创建并切换到新配置：%s',
            ['Ctrl'] = 'Ctrl',
            ['Delete profile \'%s\''] = '删除配置：“%s”',
            ['Delete profile: %s'] = '删除配置：%s',
            ['Delete this binding'] = '删除此绑定',
            ['Deleted profile: %s'] = '已删除配置：%s',
            ['Disable all bindings when in housing edit mode'] = '在房屋编辑模式下禁用所有绑定',
            ['Disabled - Gamepad not enabled'] = '已禁用 - 未启用手柄',
            ['Don\'t show this automatically'] = '不要自动显示',
            ['Don\'t show warnings for missing target/menu actions'] = '不再显示缺少目标/菜单动作的警告',
            ['Down'] = '下',
            ['Edit Binding'] = '编辑绑定',
            ['Edit Macro'] = '编辑宏',
            ['Enable GamePad binding support'] = '启用手柄绑定支持',
            ['End Quickbind'] = '结束快速绑定',
            ['Enter the name of a new profile you\'d like to create'] = '输入你想创建的新配置名称',
            ['Export bindings:'] = '导出绑定：',
            ['Filter'] = '筛选',
            ['Fix issue with health and power bars'] = '修复生命值和能量条问题',
            ['Frame Denylist'] = '框体黑名单',
            ['General Options'] = '常规选项',
            ['Generate'] = '生成',
            ['If you want to target or open the unit menu by clicking a frame, add a binding for those actions in Clique with the clicks or keypresses you prefer.'] = '如果你想通过点击框体来选中目标或打开单位菜单，请在 Clique 中为这些动作绑定你偏好的点击或按键。',
            ['Import'] = '导入',
            ['Import bindings:'] = '导入绑定：',
            ['Importing new bindings into current profile'] = '正在将新绑定导入当前配置',
            ['Include character macros'] = '包含角色宏',
            ['Include global macros'] = '包含全局宏',
            ['Include off-spec spells'] = '包含非主天赋法术',
            ['Include passive spells'] = '包含被动法术',
            ['Include spells from \'General\' tab'] = '包含“常规”标签页中的法术',
            ['Invalid!'] = '无效！',
            ['LAlt'] = '左 Alt',
            ['LCtrl'] = '左 Ctrl',
            ['LMeta'] = '左 Meta',
            ['LShift'] = '左 Shift',
            ['Later'] = '稍后',
            ['LeftButton'] = '左键点击',
            ['Macro:'] = '宏：',
            ['Macros'] = '宏',
            ['Meta'] = 'Meta',
            ['MiddleButton'] = '中键点击',
            ['Missing \'Show unit menu\' binding'] = '缺少“显示单位菜单”绑定',
            ['Missing \'Target unit\' and \'Show unit menu\' bindings'] = '缺少“目标单位”和“显示单位菜单”绑定',
            ['Missing \'Target unit\' binding'] = '缺少“目标单位”绑定',
            ['MousewheelDown'] = '滚轮向下滚动',
            ['MousewheelUp'] = '滚轮向上滚动',
            ['Multiple macros are named \'%s\'. Which one of them runs is unpredictable.'] = '存在多个名为“%s”的宏，最终运行哪一个无法确定。',
            ['New Binding'] = '新建绑定',
            ['No'] = '否',
            ['No binding set'] = '无组别',
            ['No bindings for current modifier'] = '当前修饰键下没有绑定',
            ['Non-default Blizzard Clickcast Settings Detected'] = '检测到非默认暴雪点击施法设置',
            ['Not part of any bind-sets'] = '不属于任何绑定组',
            ['Okay'] = '确定',
            ['Only active when mouse is over a unit (|cffffd100hovercast|r)'] = '仅在鼠标悬停在单位上时生效 (|cffffd100hovercast|r)',
            ['Only cast on enemy units (|cffffd100enemy|r)'] = '仅对敌方单位施放 (|cffffd100enemy|r)',
            ['Only cast on friendly units (|cffffd100friend|r)'] = '仅对友方单位施放 (|cffffd100friend|r)',
            ['Only cast when out-of-combat (|cffffd100ooc|r)'] = '仅在非战斗时施放 (|cffffd100ooc|r)',
            ['Open'] = '打开',
            ['Open Clique Options'] = '打开 Clique 选项',
            ['Open unit menu'] = '打开右键菜单',
            ['Options'] = '设置',
            ['Party member frames'] = '小队框体',
            ['Pet'] = '宠物',
            ['Player frame'] = '玩家头像',
            ['Player\'s focus frame'] = '焦点头像',
            ['Player\'s pet frame'] = '宠物头像',
            ['Player\'s target frame'] = '目标头像',
            ['Primary'] = '主',
            ['Primary Trinket'] = '主饰品',
            ['Profile Management'] = '配置管理',
            ['Profile Management:'] = '配置管理：',
            ['Profile: %s'] = '配置：%s',
            ['Quickbind Mode'] = '快速绑定模式',
            ['RAlt'] = '右 Alt',
            ['RCtrl'] = '右 Ctrl',
            ['RMeta'] = '右 Meta',
            ['RShift'] = '右 Shift',
            ['Reload Now'] = '立即重载',
            ['Remove rank/school'] = '移除等级/学派',
            ['RightButton'] = '右键点击',
            ['Run custom macro'] = '运行自定义宏',
            ['Run custom macro \'%s\''] = '运行自定义宏“%s”',
            ['Run macro'] = '运行宏',
            ['Run macro \'%s\''] = '运行宏“%s”',
            ['Save Binding'] = '保存绑定',
            ['Secondary'] = '次',
            ['Secondary Trinket'] = '副饰品',
            ['Select All'] = '选择所有',
            ['Select None'] = '清除所有选择',
            ['Select a spell or macro using the window to the right, and use the Change binding button to set a click or key binding. The binding behaviour can be configured using the settings below.'] = '请使用右侧窗口选择法术或宏，然后点击“修改绑定”按钮设置点击或按键绑定。绑定行为可以通过下方设置进行调整。',
            ['Select profile: %s'] = '选择配置：%s',
            ['Shift'] = 'Shift',
            ['Show binding tooltip on unit frames'] = '在单位框体上显示绑定提示',
            ['Show unit menu'] = '打开右键菜单',
            ['Since 12.0.7 Blizzard has made changes to the default UI that conflict with addons that overwrite actions on unit frames. For things to work properly, the in-game click-casting needs Target Unit Frame set to LeftButton and Open Context Menu set to RightButton.'] = '自 12.0.7 起，暴雪对默认界面进行了更改，这会影响覆盖单位框体动作的插件。为使功能正常工作，游戏内点击施法需将“目标单位框体”设为左键，并将“打开上下文菜单”设为右键。',
            ['Sort by binding key'] = '按绑定键排序',
            ['Sort by name'] = '按名称排序',
            ['Spells'] = '法术',
            ['Swap profiles based on talent spec'] = '随天赋切换配置',
            ['Switching to profile \'%s\''] = '正在切换到配置“%s”',
            ['Switching to profile: %s'] = '正在切换到配置：%s',
            ['Switching to profile: \'%s\''] = '正在切换到配置：“%s”',
            ['Talent profile: %s'] = '天赋配置：%s',
            ['Target clicked unit'] = '选中点击单位',
            ['Target of focus frame'] = '焦点的目标',
            ['Target of target frame'] = '目标的目标',
            ['Target unit'] = '目标单位',
            ['The \'self cast\' key is enabled and set to %s, which is also used by one or more of your bindings. This conflict may cause those spells to be cast on you instead of your desired target.'] = '“自我施法”按键已启用并设置为 %s，而你的一个或多个绑定也使用了这个按键。这会导致这些技能有可能施放在你自己身上而不是目标身上。',
            ['These options control whether or not Clique automatically registers certain Blizzard-created frames for binding. Changes made to these settings will not take effect until the user interface is reloaded.'] = '这些设置决定 Clique 是否自动为某些暴雪创建的框体注册绑定。修改后需要重载界面才会生效。',
            ['These options have moved into the main Clique config window.'] = '这些选项已移动到 Clique 主设置窗口中。',
            ['This binding is DISABLED'] = '此项设置已被禁用',
            ['This binding is invalid, please delete'] = '非法设置，请删除',
            ['This option permanently dismisses the warning on the Clique config page that shows when the menu and target actions haven\'t been bound, but has no action other than hiding that message'] = '此选项会永久隐藏 Clique 设置页面中关于菜单动作和目标动作尚未绑定的警告，仅用于关闭该提示。',
            ['This panel allows you to deny certain frames from being included for Clique bindings. Any frames that are selected in this list will not be registered. A UI reload is required for denied frames to return to their original bindings.'] = '此面板允许你将某些框体加入黑名单，避免它们被 Clique 注册为绑定目标。被选中的框体将不会被注册，且需要重载界面后才能恢复原有绑定。',
            ['This will add the imported bindings to your current profile. Are you sure?'] = '这会将导入的绑定添加到当前配置中。你确定吗？',
            ['This will replace all bindings in your current profile with the imported bindings. Are you sure?'] = '这会用导入的绑定替换当前配置中的所有绑定。你确定吗？',
            ['This works best with unique macro names, or you can use the Run Custom Macro action.'] = '使用唯一的宏名效果最好，或者你也可以使用“运行自定义宏”动作。',
            ['Tooltip anchor:'] = '提示信息锚点：',
            ['Trigger bindings on:'] = '绑定触发于：',
            ['Unknown'] = '未知',
            ['Unknown binding type \'%s\''] = '未知绑定类型“%s”',
            ['Up'] = '上',
            ['Use item: %s'] = '使用物品：%s',
            ['Use item: Primary Trinket'] = '使用物品：主饰品',
            ['Use item: Secondary Trinket'] = '使用物品：副饰品',
            ['Validate'] = '校验',
            ['What\'s New'] = '新内容',
            ['Yes'] = '是',
            ['You are in binding capture mode! You can either click with your mouse or press a key on your keyboard to set a binding. You can modify the binding by holding down a combination of the alt, control and shift keys on your keyboard.'] = '你正在进行绑定捕获模式！你可以点击鼠标或按下键盘上的按键来设置绑定。你也可以同时按住 Alt、Ctrl 和 Shift 等组合键来修改绑定。',
            ['You are in quick-bind mode. Mouse over spells and macros in the catalog window to quickly bind and add actions. You can use any combinmation of alt, control and shift with your clicks and key-presses'] = '你正在进行快速绑定模式。把鼠标悬停在目录窗口中的法术和宏上即可快速绑定并添加动作。你可以在点击或按键时同时使用 Alt、Ctrl 和 Shift。',
            ['You are in quickbind mode, you can use a click or press a key to add a binding'] = '你正在进行快速绑定模式，你可以通过点击或按下按键来添加绑定',
            ['character'] = '角色',
            ['global'] = '全局',
            ['pet'] = '宠物',
            ['|cff22ff22Changed|r: %s'] = '|cff22ff22已更改|r: %s',
            ['|cffFF4800Ambiguous macro name'] = '|cffFF4800宏名有歧义',
            ['|cffFF4800No macros with name \'%s\' exists'] = '|cffFF4800不存在名为“%s”的宏',
        })
    end
end)
