-- .index.lua
-- @Author : Dencer (tdaddon@163.com)
-- @Link   : https://dengsir.github.io
-- @Date   : 7/20/2020, 10:00:50 AM

---@class tdUIMinimapButtonOpt
---@field collected boolean
---@field SetPoint function
---@field ClearAllPoints function
---@field OnEnter function
---@field OnDragStart function
---@field OnDragStop function
---@field points table
---@field frameLevelDelta number
